
package model;


public class CacMonHoc {
    public CacMonHoc()
    {
        
    }
    public String[] IT_TienTrinh = {
            "Triết học Mác-Lênin",
            "Giải tích 1",
            "Tin học cơ sở 1",
            "Đại số",
            "Kinh tế chính trị Mác-Lênin",
            "Tiếng anh Course 1",
            "Giải tích 2",
            "Vật lý ứng dụng",
            "Tin học cơ sở 2",
            "Kỹ thuật số",
            "Pháp luật đại cương",
            "Chủ nghĩa xã hội khoa học",
            "Tiếng anh Course 2",
            "Toán rời rạc 1",
            "Xử lý tín hiệu số",
            "Ngôn ngữ lập trình C++",
            "Xác suất thống kê",
            "Kỹ năng mềm 1",
            "Tư tưởng Hồ Chí Minh",
            "Tiếng anh Course 3",
            "Kiến trúc máy tính",
            "Toán rời rạc 2",
            "Cấu trúc dữ liệu và giải thuật",
            "Lý thuyết thông tin",
            "Kỹ năng mềm 2",
            "Lịch sử Đảng Cộng Sản Việt Nam",
            "Lập trình với Python",
            "Hệ điều hành",
            "Mạng máy tính",
            "Lập trình hướng đối tượng",
            "Cơ sở dữ liệu",
            "Tiếng anh Course 3+",
            "Lập trình web",
            "An toàn và bảo mật hệ thống thông tin",
            "Nhập môn công nghệ phần mềm",
            "Nhập môn trí tuệ nhân tạo",
            "Cơ sở dữ liệu phân tán",
            "Thực tập cơ sở",
            "Quản lý dự án phần mềm",
            "Phát triển các hệ thống thông minh",
            "Xử lý ảnh",
            "Phân tích và thiết kế HTTT",
            "IOT và ứng dụng",
            "Học phần tự chọn",
            "Phương pháp luận NCKH",
            "Đảm bảo chất lượng phần mềm",
            "Phát triển phần mềm hướng dịch vụ",
            "Phát triển ứng dụng cho các thiết bị di động",
            "Kiến trúc và thiết kế phần mềm",
            "Xây dựng các hệ thống nhúng",
            "Chuyên đề Công nghệ phần mềm"
        };
        public String[] BC_TienTrinh = {
    "Triết học Mác-Lênin",
    "Cơ sở lý luận báo chí truyền thông",
    "Phương pháp luận NCKH",
    "Cơ sở văn hóa Việt Nam",
    "Tin học cơ sở 1",
    "Kinh tế chính trị Mác-Lênin",
    "Tiếng anh Course 1",
    "Văn hóa và truyền thông đại chúng",
    "Logic học đại cương",
    "Tâm lý học báo chí",
    "Tiếng Việt thực hành",
    "Mỹ thuật đại cương",
    "Tin học cơ sở 3",
    "Chủ nghĩa xã hội khoa học",
    "Pháp luật, Đạo đức và Lao động báo chí",
    "Tiếng anh Course 2",
    "Các loại hình báo chí",
    "Nhập môn thiết kế và sự sáng tạo trong báo chí",
    "Nhiếp ảnh báo chí",
    "Nhập môn công nghệ báo chí số",
    "Tư tưởng Hồ Chí Minh",
    "Tiếng anh Course 3",
    "Ngôn ngữ báo chí và sáng tạo tác phẩm báo chí",
    "Thiết kế đồ họa báo chí",
    "Kỹ thuật Quay và dựng video",
    "Kịch bản cho tác phẩm báo chí số",
    "Tiếng anh Course 3+",
    "Kinh tế báo chí",
    "Thương hiệu và xây dựng thương hiệu trong báo chí",
    "Công cụ xử lý hiệu ứng trong báo chí số",
    "Báo chí dữ liệu",
    "Lịch sử Đảng Cộng Sản Việt Nam",
    "Nghệ thuật chữ ",
    "Báo chí và phương tiện truyền thông XH",
    "Internet và công nghệ web",
    "Thiết kế minh họa trong báo chí số",
    "Viết chuyên nghiệp",
    "Thu thập và xử lý dữ liệu báo chí số",
    "3 Học phần tự chọn",
    "Dẫn chương trình",
    "Vận hành tòa soạn báo chí số",
    "Công nghệ AI trong phân tích dữ liệu báo chí số",
    "Báo chí và dư luận xã hội",
    "Báo chí đương đại",
    "3 Học phần tự chọn",
    "Thực tập và tốt nghiệp "
};
        public String[] KHMT_TienTrinh = {
    "Triết học Mác-Lênin",
    "Giải tích 1",
    "Tin học cơ sơ 1",
    "Đại số",
    "Kinh tế chính trị Mác-Lênin",
    "Tiếng anh Course 1",
    "Vật lý 1 và thí nghiệm",
    "Giải tích 2",
    "Tin học cơ sở 2",
    "Kỹ thuật số",
    "Xác suất thống kê",
    "Chủ nghĩ xã hội khoa học",
    "Tiếng anh Course 2",
    "Vật lý 3 và thí nghiệm",
    "Toán rời rạc 1",
    "Ngôn ngữ C++",
    "Xử lý tín hiệu số",
    "Tư tưởng Hồ Chí Minh",
    "Tiếng anh Course 3",
    "Kiến trúc máy tính",
    "Toán rời rạc 2",
    "Cấu trúc dữ liệu và giải thuật",
    "Lý thuyết thông tin",
    "Lịch sử Đảng Cộng Sản Việt Nam",
    "Tiếng anh Course 3+",
    "Hệ điều hành",
    "Lập trình với python",
    "Lập trình hướng đối tượng",
    "Mạng máy tính",
    "Cơ sở dữ liệu",
    "Nhập môn trí tuệ nhân tạo",
    "An toàn và bảo mật hệ thống thông tin",
    "Nhập môn công nghệ phần mềm",
    "Lập trình web",
    "Hệ quản trị cơ sở dữ liệu",
    "Thực tập cơ sở",
    "Phương pháp luận NCKH",
    "Xử lý ảnh",
    "Học máy",
    "Phân tích và thiết kế HTTT",
    "Nhập học khoa học dữ liệu",
    "Học phần tự chọn",
    "Nhập môn học sâu",
    "Khai phá dữ liệu lớn",
    "Học phần tự chọn 1",
    "Học phần tự chọn 2",
    "Học phần tự chọn 3",
    "Học phần tự chọn 4"
};
        public String[] QT_TienTrinh  = {
    "Triết học Mác-Lênin",
    "Tâm lý quản lý",
    "Tin học cơ sở 1",
    "Toán cao cấp 1",
    "Pháp luật đại cương",
    "Kinh tế chính trị Mác-Lênin",
    "Tiếng Anh (Course 1)",
    "Toán cao cấp 2",
    "Lý thuyết xác suất và thống kê",
    "Tin học cơ sở 3",
    "Kinh tế vi mô 1",
    "Chủ nghĩa xã hội khoa học",
    "Tiếng Anh (Course 2)",
    "Toán kinh tế",
    "Kinh tế vĩ mô 1",
    "Marketing căn bản",
    "Quản trị học",
    "Lịch sử Đảng cộng sản Việt Nam",
    "Tiếng Anh (Course 3)",
    "Nguyên lý kế toán",
    "Tài chính tiền tệ",
    "Giao tiếp trong kinh doanh",
    "Thương mại điện tử căn bản",
    "Kinh tế lượng",
    "Tư tưởng Hồ Chí Minh",
    "Tiếng Anh (Course 3 Plus)",
    "Quản trị sản xuất",
    "Thống kê doanh nghiệp",
    "Logistics căn bản",
    "Hệ thống thông tin quản lý",
    "Quản trị chiến lược",
    "Quản trị tài chính doanh nghiệp",
    "Kế toán quản trị",
    "Luật kinh doanh",
    "Quản trị bán hàng và phân phối sản phẩm",
    "Quản trị nhân lực",
    "Phân tích hoạt động sản xuất kinh doanh",
    "2 học phần tự chọn",
    "Phương pháp luận NCKH",
    "Quản trị marketing",
    "Khởi sự kinh doanh",
    "Quản trị doanh nghiệp",
    "Kinh doanh quốc tế",
    "Quản trị đổi mới sáng tạo",
    "2 học phần tự chọn",
    "Thực tập và tốt nghiệp "
};
        public String[] MK_TienTrinh = {
    "Triết học Mác-Lênin",
    "Tâm lý quản lý",
    "Tin học cơ sở 1",
    "Toán cao cấp 1",
    "Pháp luật đại cương",
    "Kinh tế chính trị Mác-Lênin",
    "Tiếng Anh (Course 1)",
    "Toán cao cấp 2",
    "Lý thuyết xác suất và thống kê",
    "Tin học cơ sở 3",
    "Kinh tế vi mô 1",
    "Chủ nghĩa xã hội khoa học",
    "Tiếng Anh (Course 2)",
    "Toán kinh tế",
    "Kinh tế vĩ mô 1",
    "Marketing căn bản",
    "Tư tưởng Hồ Chí Minh",
    "Tiếng Anh (Course 3)",
    "Nguyên lý kế toán",
    "Quản trị học",
    "Hành vi khách hàng",
    "Quản trị Marketing",
    "Internet và ứng dụng trong kinh doanh",
    "Lịch sử Đảng cộng sản VN",
    "Tiếng Anh (Course 3 Plus)",
    "Kinh tế lượng",
    "Các hệ thống thông tin trong DN",
    "Quản lý dự án",
    "Marketing dịch vụ",
    "Thương mại điện tử",
    "Phát triển và ứng dụng web trong Marketing",
    "Phương pháp nghiên cứu Marketing",
    "Marketing công nghiệp",
    "Ứng dụng ĐPT trong kinh doanh",
    "Truyền thông Marketing tích hợp",
    "Quản trị cơ sở dữ liệu kinh doanh",
    "E-Marketing",
    "03 học phần tự chọn",
    "Phương pháp luận NCKH",
    "Phân tích web",
    "Marketing qua phương tiện truyền thông XH",
    "Tổng quan về biên tập web",
    "Marketing bằng công cụ tìm kiếm",
    "Đề án: Kế hoạch Internet Marketing",
    "Thực tập và tốt nghiệp "
};

}
