
package view;

import controller.SinhVienDAO;
import controller.TienTrinhDAO;
import controller.TkbDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DangKiMon;
import model.LopHocPhan;
import model.SinhVien;
import model.TienTrinh;


public class GD_CapNhapDiem extends javax.swing.JFrame implements ActionListener{
    DefaultTableModel model;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GD_CapNhapDiem.class.getName());

    private SinhVienDAO sinhVienDAO;
    private TienTrinhDAO tienTrinhDAO;
    private LopHocPhan lopHocPhan;
    private SinhVien sinhVien;
    private ArrayList<DangKiMon> list;
    private ArrayList<SinhVien> list2 = new ArrayList<>();
    public GD_CapNhapDiem(LopHocPhan l) {
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        sinhVienDAO = new SinhVienDAO();
        tienTrinhDAO = new TienTrinhDAO();
        lopHocPhan = l;
        CapNhapButton.addActionListener(this);
        BackButton.addActionListener(this);
        list = new TkbDAO().getListDKM(l.getMaLHP());
        model = (DefaultTableModel) SuaDiemTable.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new Object[]{
            "MaSV","Họ và tên","Kết quả"
        });
        for(DangKiMon  i : list)
        {
            SinhVien tmp = new SinhVienDAO().getSinhVien(i.getMaSV());
            list2.add(tmp);
        }
        for(SinhVien i : list2)
        {
            TienTrinh t = new TienTrinhDAO().getTienTrinh2SV(i.getId());
            model.addRow(new Object[]{
                i.getId(),i.getName(),String.valueOf(t.getKetQua())
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SuaDiemTable = new javax.swing.JTable();
        CapNhapButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CẬP NHẬP ĐIỂM ");

        SuaDiemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(SuaDiemTable);

        CapNhapButton.setText("Cập nhập");

        BackButton.setText("Quay lại ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CapNhapButton)
                        .addGap(232, 232, 232))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BackButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(CapNhapButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CapNhapButton;
    private javax.swing.JTable SuaDiemTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void actionPerformed(ActionEvent e)
    {
        
        if(e.getSource().equals(CapNhapButton)) btnCapNhapClick();
        else
        {
            this.dispose();
        }
     }
    
    public void btnCapNhapClick()
    {
        TienTrinh t = new TienTrinh();
        for(int i = 0;i<model.getRowCount();i++)
        {
            t.setId(String.valueOf(model.getValueAt(i, 0)));
            try {
                float tmp = Float.parseFloat(model.getValueAt(i, 2).toString());
                System.out.println(tmp);
                t.setKetQua(tmp);

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Lỗi định dạng điểm nhập vào !");
            }
            t.setMaMon(lopHocPhan.getMaMon());
            if(new TienTrinhDAO().SetDiem(t))
            {
                System.out.println("Cap nhap diem thanh cong cho hs" + i);
            }
        }
    }
}
