
package view;

import controller.SinhVienDAO;
import controller.TienTrinhDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.SinhVien;
import model.TienTrinh;


public class GD_CapNhapDiem extends javax.swing.JFrame implements ActionListener{
    DefaultTableModel model;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GD_CapNhapDiem.class.getName());

    private SinhVienDAO sinhVienDAO;
    private TienTrinhDAO tienTrinhDAO;
    
    public GD_CapNhapDiem() {
        initComponents();
        
        sinhVienDAO = new SinhVienDAO();
        tienTrinhDAO = new TienTrinhDAO();
        
        TimSinhVienButton.addActionListener(this);
        CapNhapButton.addActionListener(this);
        BackButton.addActionListener(this);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IdTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        SuaDiemTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        KiHocTextField = new javax.swing.JTextField();
        TimSinhVienButton = new javax.swing.JButton();
        CapNhapButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CẬP NHẬP ĐIỂM ");

        jLabel2.setText("ID:");

        SuaDiemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(SuaDiemTable);

        jLabel3.setText("Kì học:");

        TimSinhVienButton.setText("Tìm");

        CapNhapButton.setText("Cập nhập");

        BackButton.setText("Quay lại ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KiHocTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TimSinhVienButton)
                        .addGap(237, 237, 237))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CapNhapButton)
                        .addGap(232, 232, 232))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BackButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(KiHocTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TimSinhVienButton)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CapNhapButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GD_CapNhapDiem().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CapNhapButton;
    private javax.swing.JTextField IdTextField;
    private javax.swing.JTextField KiHocTextField;
    private javax.swing.JTable SuaDiemTable;
    private javax.swing.JButton TimSinhVienButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void actionPerformed(ActionEvent e)
    {
        if(e.getSource().equals(TimSinhVienButton)) btnTimClick();
        else if(e.getSource().equals(CapNhapButton)) btnCapNhapClick();
        else
        {
            GD_Menu_Admin winAdmin = new GD_Menu_Admin();
            winAdmin.setLocationRelativeTo(null);
            winAdmin.setVisible(true);
            this.dispose();
        }
     }
    public void btnTimClick()
    {
        SinhVien NewSinhVien = sinhVienDAO.getSinhVien(IdTextField.getText());
        ArrayList<TienTrinh> NewTienTrinh = tienTrinhDAO.getTienTrinh(NewSinhVien);
        model = (DefaultTableModel) SuaDiemTable.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new Object[]{
            "STT","Tên môn","Kết quả"
        });
        int cnt=1;
        for(TienTrinh i : NewTienTrinh)
        {
            if(i.getHocKi() == Integer.parseInt(KiHocTextField.getText()))
            {
                model.addRow(new Object[]{
                    cnt,i.getTenMon(),i.getKetQua()
                });
                cnt+=1;
            }
        }
    }
    public void btnCapNhapClick()
    {
        SinhVien NewSinhVien = sinhVienDAO.getSinhVien(IdTextField.getText());
        TienTrinh tr = new TienTrinh();
        tr.setId(NewSinhVien.getId());
        tr.setHocKi(Integer.parseInt(KiHocTextField.getText()));
        tr.setChuyenNganh(NewSinhVien.getMajor());
        for(int i = 0;i<model.getRowCount();i++)
        {
            tr.setTenMon(model.getValueAt(i, 1).toString());
            try {
                tr.setKetQua(Float.parseFloat(model.getValueAt(i, 2).toString()));
            } catch (NumberFormatException e) {
                tr.setKetQua(0);
            }
            if(new TienTrinhDAO().SetDiem(tr) == false) JOptionPane.showMessageDialog(rootPane, "Cập nhập điểm thất bại!");
        }
        JOptionPane.showMessageDialog(rootPane, "Cập nhật điểm thành công!");
    }
}
