
package view;

import controller.TaiKhoanDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import model.SinhVien;
import model.TaiKhoan;

public class GD_DoiMk extends javax.swing.JFrame implements ActionListener{
    public SinhVien sinhVien;
    public TaiKhoan taiKhoan;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GD_DoiMk.class.getName());

    private TaiKhoanDAO taiKhoanDAO;
    
    public GD_DoiMk(SinhVien s) {
        initComponents();
        sinhVien = s;
        
        taiKhoanDAO = new TaiKhoanDAO();
        
        CapNhapButton.addActionListener(this);
        ResetButton.addActionListener(this);
        BackButton.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel1 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          XacNhanTextField = new javax.swing.JPasswordField();
          MatKhauMoiTextField = new javax.swing.JPasswordField();
          CapNhapButton = new javax.swing.JButton();
          ResetButton = new javax.swing.JButton();
          BackButton = new javax.swing.JButton();
          MatKhauCuTextField = new javax.swing.JPasswordField();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
          jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel1.setText("ĐỔI MẬT KHẨU");

          jLabel3.setText("Mật khẩu cũ:");

          jLabel4.setText("Mật khẩu mới:");

          jLabel5.setText("Xác nhận mật khẩu:");

          CapNhapButton.setText("Cập nhập ");

          ResetButton.setText("Reset");

          BackButton.setText("Quay lại");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(CapNhapButton)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jLabel5)
                              .addComponent(jLabel4)
                              .addComponent(jLabel3)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                              .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(84, 84, 84))
                         .addGroup(layout.createSequentialGroup()
                              .addGap(18, 18, 18)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(XacNhanTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                   .addComponent(MatKhauMoiTextField)
                                   .addComponent(MatKhauCuTextField))
                              .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(BackButton)
                    .addGap(0, 0, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel3)
                         .addComponent(MatKhauCuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel4)
                         .addComponent(MatKhauMoiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel5)
                         .addComponent(XacNhanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(32, 32, 32)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(CapNhapButton)
                         .addComponent(ResetButton))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                    .addComponent(BackButton)
                    .addContainerGap())
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton BackButton;
     private javax.swing.JButton CapNhapButton;
     private javax.swing.JPasswordField MatKhauCuTextField;
     private javax.swing.JPasswordField MatKhauMoiTextField;
     private javax.swing.JButton ResetButton;
     private javax.swing.JPasswordField XacNhanTextField;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     // End of variables declaration//GEN-END:variables
    @Override
    public void actionPerformed(ActionEvent e)
    {
        if(e.getSource().equals(CapNhapButton)) btnCapNhapClick();
        else if(e.getSource().equals(ResetButton))
        {
            MatKhauCuTextField.setText("");
            MatKhauMoiTextField.setText("");
            XacNhanTextField.setText("");
        }
        else
        {
            GD_Menu_SV winD_Menu_SV = new GD_Menu_SV(sinhVien);
            winD_Menu_SV.setLocationRelativeTo(null);
            winD_Menu_SV.setVisible(true);
            this.dispose();
        }
     }
    public void btnCapNhapClick()
    {
        TaiKhoan tk = taiKhoanDAO.getTaiKhoan(sinhVien);
        char[] temp2 = MatKhauMoiTextField.getPassword();
        char[] temp3 = XacNhanTextField.getPassword();
        String NewMk  = new String(temp2);
        String XacNhanMk = new String(temp3);
        if(MatKhauCuTextField.getText().equals(tk.getPassWord()))
        {
            if(NewMk.equals(XacNhanMk))
            {
                char[] temp = XacNhanTextField.getPassword();
                String Npass = new String(temp);
                if(taiKhoanDAO.DoiMatKhau(sinhVien, Npass))
                {
                    JOptionPane.showMessageDialog(rootPane, "Đổi mật khẩu thành công !");
                }
                else JOptionPane.showMessageDialog(rootPane, "Đổi mật khẩu thất bại !");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Mật khẩu xác nhận không trùng với mật khẩu mới !");
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu sai !");
        }
    }

}
