/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.TienTrinhDAO;
import controller.TkbDAO;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Properties;
import javax.swing.AbstractCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import model.GiangVien;
import model.LopHocPhan;
import model.MonHoc;
import model.NhanVien;
import model.SinhVien;
import model.TienTrinh;

/**
 *
 * @author ThanhNguyen
 */
public class GD_DangKiLopGiangDay extends javax.swing.JFrame implements ActionListener{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GD_DangKiLopGiangDay.class.getName());
    private DefaultTableModel model;
    private ArrayList<TienTrinh> list;
    private GiangVien giangVien;
    /**
     * Creates new form GD_DangKiMon
     */
    public GD_DangKiLopGiangDay(GiangVien s) {
        initComponents();
        pack();
        Properties prop = new Properties();
        try {
            InputStream input = getClass().getResourceAsStream("/config.properties");
            if(input != null) {
                prop.load(input);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        String bgColor = prop.getProperty("backgroundColor", "255,255,255"); // default trắng
        String[] rgb = bgColor.split(",");
        int r = Integer.parseInt(rgb[0].trim());
        int g = Integer.parseInt(rgb[1].trim());
        int b = Integer.parseInt(rgb[2].trim());
        getContentPane().setBackground(new Color(r, g, b));
        
        //------------------------------------------------
        giangVien = s;
        BackButton.addActionListener(this);
        TenMonCheckBox.addActionListener(this);
        KiHocCombobox.addActionListener(this);
        model = (DefaultTableModel) MonHocTable.getModel();
        model.setColumnIdentifiers(new Object[]{
            "Mã môn","Tên môn","Phòng Học","Tiết bắt đầu","Số tiết","Thứ","Thời gian","Thao tác"
        });
        ArrayList<MonHoc> list  = new ArrayList<>();
        list = new TkbDAO().getListMonHoc(giangVien.getKhoa(),Integer.parseInt(KiHocCombobox.getSelectedItem().toString()));
        for(MonHoc i : list)
        {
            TenMonCheckBox.addItem(i.getTenMon());
        }
        model.setRowCount(0);
        ShowData(list);
        int columIndex = 7;
        MonHocTable.getColumnModel().getColumn(columIndex).setCellRenderer(new ButtonRenderer6());
        MonHocTable.getColumnModel().getColumn(columIndex).setCellEditor(new ButtonEditor6(giangVien,Integer.parseInt(KiHocCombobox.getSelectedItem().toString())));
        
    }
    
    public void ShowData(ArrayList<MonHoc> list)
    {
        int[] haitiet = {1,7};
        int[] batiet = {3,9};
        
        for(int i =2;i<=7;i++)
        {
            for(int j : haitiet)
            {
                model.addRow(new Object[]{
                   list.get(TenMonCheckBox.getSelectedIndex()).getMaMon(),TenMonCheckBox.getSelectedItem().toString(),String.valueOf(j)+"0"+String.valueOf(TenMonCheckBox.getSelectedIndex()+1),j,2,i,(Integer.parseInt(KiHocCombobox.getSelectedItem().toString()) % 2 == 0)? "Từ 01/02 đến 31/05" : "Từ 15/08 đến 31/12","Đăng kí"
                });
            }
            for(int j : batiet)
            {
                model.addRow(new Object[]{
                    list.get(TenMonCheckBox.getSelectedIndex()).getMaMon(),TenMonCheckBox.getSelectedItem().toString(),String.valueOf(j)+"0"+String.valueOf(TenMonCheckBox.getSelectedIndex()+1),j,3,i,(Integer.parseInt(KiHocCombobox.getSelectedItem().toString()) % 2 == 0)? "Từ 01/02 đến 31/05" : "Từ 15/08 đến 31/12","Đăng kí"
                });
            }
           
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TenMonCheckBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        MonHocTable = new javax.swing.JTable();
        BackButton = new javax.swing.JButton();
        KiHocCombobox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐĂNG KÍ MÔN HỌC");

        jLabel2.setText("Tên môn:");

        MonHocTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(MonHocTable);

        BackButton.setText("Back");

        KiHocCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        jLabel3.setText("Kì học:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TenMonCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(KiHocCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TenMonCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KiHocCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JComboBox<String> KiHocCombobox;
    private javax.swing.JTable MonHocTable;
    private javax.swing.JComboBox<String> TenMonCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void actionPerformed(ActionEvent e)
    {
        if(e.getSource().equals(KiHocCombobox)) btnKihocClick();
        else if(e.getSource().equals(TenMonCheckBox)) btnTenmonClick();
        else btnBackButtonClick();
    }
    public void btnKihocClick()
    {
        TenMonCheckBox.removeAllItems();
        ArrayList<MonHoc> list;
        list = new TkbDAO().getListMonHoc(giangVien.getKhoa(),Integer.parseInt(KiHocCombobox.getSelectedItem().toString()));
        for(MonHoc i : list)
        {
            TenMonCheckBox.addItem(i.getTenMon());
            System.out.println("da chay");
        }
        model.setRowCount(0);
        ShowData(list);
        int columIndex = 7;
        MonHocTable.getColumnModel().getColumn(columIndex).setCellRenderer(new ButtonRenderer6());
        MonHocTable.getColumnModel().getColumn(columIndex).setCellEditor(new ButtonEditor6(giangVien,Integer.parseInt(KiHocCombobox.getSelectedItem().toString())));
        
    }
    public void btnTenmonClick()
    {
        int selectedIndex = TenMonCheckBox.getSelectedIndex();
        if(selectedIndex == -1) return;
        ArrayList<MonHoc> list  = new ArrayList<>();
        list = new TkbDAO().getListMonHoc(giangVien.getKhoa(),Integer.parseInt(KiHocCombobox.getSelectedItem().toString()));
        model.setRowCount(0);
        ShowData(list);
        int columIndex = 7;
        MonHocTable.getColumnModel().getColumn(columIndex).setCellRenderer(new ButtonRenderer6());
        MonHocTable.getColumnModel().getColumn(columIndex).setCellEditor(new ButtonEditor6(giangVien,Integer.parseInt(KiHocCombobox.getSelectedItem().toString())));
    }
    public void btnBackButtonClick()
    {
        GD_Menu_GV winD_Menu_SV = new GD_Menu_GV(giangVien);
        winD_Menu_SV.setLocationRelativeTo(null);
        winD_Menu_SV.setVisible(true);
        this.dispose();
    }
}
class ButtonRenderer6 extends JButton implements TableCellRenderer
{
    public ButtonRenderer6()
    {
        setOpaque(true);
        
    }
    @Override
    public Component getTableCellRendererComponent(JTable table,Object value,boolean isSelected, boolean hasFocus,int row, int column)
    {
        setText((value == null)? "Đăng kí": value.toString());
        return this;
    }
}
class ButtonEditor6 extends AbstractCellEditor implements TableCellEditor, ActionListener
{
    private JButton button;
    private JTable table;
    private int currentRow;
    private GiangVien giangVien;
    private int kihoc;
    public ButtonEditor6(GiangVien s,int t)
    {
        giangVien = s;
        button = new JButton("Đăng kí");
        button.setOpaque(true);
        button.addActionListener(this);
        kihoc = t;
    }
    @Override
    public Component getTableCellEditorComponent(JTable table, Object value,boolean isSelected, int row, int column)
    {
        this.table = table;
        this.currentRow = row;
        button.setText((value == null)? "Đăng kí":value.toString());
        return button;
    }
    @Override
    public Object getCellEditorValue()
    {
        return button.getText();
    }
    @Override
    public void actionPerformed(ActionEvent e)
    {
        LopHocPhan l = new LopHocPhan();
        l.setMaGV(giangVien.getID());
        l.setMaMon(table.getValueAt(currentRow, 0).toString());
        l.setPhong(table.getValueAt(currentRow, 2).toString());
        l.setTietBatDau(Integer.parseInt(table.getValueAt(currentRow, 3).toString()));
        l.setSoTiet(Integer.parseInt(table.getValueAt(currentRow, 4).toString()));
        l.setThu(table.getValueAt(currentRow, 5).toString());
        l.setThoiGian(table.getValueAt(currentRow, 6).toString());
        l.setKiHoc(kihoc);
        
        if(new TkbDAO().CapNhapLHP(l))
            {
                JOptionPane.showMessageDialog(null, "Cập nhập thời khóa biểu thành công !");
            }
        else{
                JOptionPane.showMessageDialog(null, "Trùng lịch học với môn khác hoặc môn học đã được đăng kí");
            }
        
        
    }

    @Override
    protected void fireEditingStopped() {
        super.fireEditingStopped(); 
    }
    
}