
package view;

import controller.NhanVienDAO;
import controller.SinhVienDAO;
import controller.TienTrinhDAO;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import model.SinhVien;
import java.io.File;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import java.awt.Image;
import java.io.InputStream;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.NhanVien;



public class GD_Menu_Admin1 extends javax.swing.JFrame implements ActionListener{
    public NhanVien nhanVien;
    private File selectFile;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GD_Menu_Admin1.class.getName());

    private NhanVienDAO nhanVienDAO;
    private TienTrinhDAO tienTrinhDAO;
    
    public GD_Menu_Admin1(NhanVien s) {
        initComponents();
        
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        nhanVienDAO = new NhanVienDAO();
        tienTrinhDAO = new TienTrinhDAO();
        
        nhanVien = s;
        AddGvButton.addActionListener(this);
        AddButton.addActionListener(this);
        UpdateButton.addActionListener(this);
        AddNvButton.addActionListener(this);
        ThemAnhButton.addActionListener(this);
        BackButton1.addActionListener(this);
        ChangePwButton1.addActionListener(this);
        TenLabel.setText(s.getName());
        MsvLabel.setText(s.getId());
       
       
        DobLabel.setText(s.getDob().toString());
        ImageIcon avatar = nhanVienDAO.getAvatar(MsvLabel.getText());
        if (avatar != null) {
            AvatarLabel.setIcon(avatar);
            AvatarLabel.setText("");
        } else {
            AvatarLabel.setIcon(null);
            AvatarLabel.setText("Chưa có ảnh");
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        TenLabel = new javax.swing.JLabel();
        MsvLabel = new javax.swing.JLabel();
        AvatarLabel = new javax.swing.JLabel();
        LopLabel = new javax.swing.JLabel();
        ChuyenNganhLabel = new javax.swing.JLabel();
        GioiTinhLabel = new javax.swing.JLabel();
        NgaySinhLabel = new javax.swing.JLabel();
        DiaChiLabel = new javax.swing.JLabel();
        NamHocLabel = new javax.swing.JLabel();
        SoDienThoaiLabel = new javax.swing.JLabel();
        TrangThaiLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        CpaLabel = new javax.swing.JLabel();
        DobLabel = new javax.swing.JLabel();
        ThemAnhButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddGvButton = new javax.swing.JButton();
        BackButton1 = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        AddNvButton = new javax.swing.JButton();
        ChangePwButton1 = new javax.swing.JButton();

        jLabel17.setText("jLabel17");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ SINH VIÊN [USER]");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TenLabel.setBackground(new java.awt.Color(255, 255, 255));
        TenLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TenLabel.setOpaque(true);
        getContentPane().add(TenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 233, 170, 22));

        MsvLabel.setBackground(new java.awt.Color(255, 255, 255));
        MsvLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MsvLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MsvLabel.setOpaque(true);
        getContentPane().add(MsvLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 267, 170, 20));

        AvatarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AvatarLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(AvatarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 127, 140));

        LopLabel.setBackground(new java.awt.Color(255, 255, 255));
        LopLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LopLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LopLabel.setOpaque(true);
        getContentPane().add(LopLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 327, -1, -1));

        ChuyenNganhLabel.setBackground(new java.awt.Color(255, 255, 255));
        ChuyenNganhLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ChuyenNganhLabel.setOpaque(true);
        getContentPane().add(ChuyenNganhLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 87, 232, -1));

        GioiTinhLabel.setBackground(new java.awt.Color(255, 255, 255));
        GioiTinhLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GioiTinhLabel.setOpaque(true);
        getContentPane().add(GioiTinhLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 93, 232, -1));

        NgaySinhLabel.setBackground(new java.awt.Color(255, 255, 255));
        NgaySinhLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NgaySinhLabel.setOpaque(true);
        getContentPane().add(NgaySinhLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 105, 232, -1));

        DiaChiLabel.setBackground(new java.awt.Color(255, 255, 255));
        DiaChiLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DiaChiLabel.setOpaque(true);
        getContentPane().add(DiaChiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 117, 237, -1));

        NamHocLabel.setBackground(new java.awt.Color(255, 255, 255));
        NamHocLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NamHocLabel.setOpaque(true);
        getContentPane().add(NamHocLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 158, 237, -1));

        SoDienThoaiLabel.setBackground(new java.awt.Color(255, 255, 255));
        SoDienThoaiLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SoDienThoaiLabel.setOpaque(true);
        getContentPane().add(SoDienThoaiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 233, 237, -1));

        TrangThaiLabel.setBackground(new java.awt.Color(255, 255, 255));
        TrangThaiLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TrangThaiLabel.setOpaque(true);
        getContentPane().add(TrangThaiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 245, 237, -1));

        EmailLabel.setBackground(new java.awt.Color(255, 255, 255));
        EmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailLabel.setOpaque(true);
        getContentPane().add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 257, 237, -1));

        CpaLabel.setBackground(new java.awt.Color(255, 255, 255));
        CpaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CpaLabel.setOpaque(true);
        getContentPane().add(CpaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 269, 237, -1));

        DobLabel.setBackground(new java.awt.Color(255, 255, 255));
        DobLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DobLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DobLabel.setOpaque(true);
        getContentPane().add(DobLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 299, 170, 22));

        ThemAnhButton.setText("Thêm ảnh");
        ThemAnhButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemAnhButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ThemAnhButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRANG NHÂN VIÊN");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 320, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("MENU:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        AddGvButton.setText("Thêm giảng viên");
        getContentPane().add(AddGvButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 400, 40));

        BackButton1.setText("Đăng xuất");
        getContentPane().add(BackButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        AddButton.setText("Thêm sinh viên");
        getContentPane().add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 400, 40));

        UpdateButton.setText("Cập nhập thông tin sinh viên");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 400, 40));

        AddNvButton.setText("Thêm admin mới");
        getContentPane().add(AddNvButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 400, 40));

        ChangePwButton1.setText("Đổi mật khẩu");
        getContentPane().add(ChangePwButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 400, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThemAnhButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemAnhButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThemAnhButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new GD_Menu_SV(SinhVien s).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton AddGvButton;
    private javax.swing.JButton AddNvButton;
    private javax.swing.JLabel AvatarLabel;
    private javax.swing.JButton BackButton1;
    private javax.swing.JButton ChangePwButton1;
    private javax.swing.JLabel ChuyenNganhLabel;
    private javax.swing.JLabel CpaLabel;
    private javax.swing.JLabel DiaChiLabel;
    private javax.swing.JLabel DobLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel GioiTinhLabel;
    private javax.swing.JLabel LopLabel;
    private javax.swing.JLabel MsvLabel;
    private javax.swing.JLabel NamHocLabel;
    private javax.swing.JLabel NgaySinhLabel;
    private javax.swing.JLabel SoDienThoaiLabel;
    private javax.swing.JLabel TenLabel;
    private javax.swing.JButton ThemAnhButton;
    private javax.swing.JLabel TrangThaiLabel;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    @Override
    public void actionPerformed(ActionEvent e)
    {
        if(e.getSource().equals(AddButton)) btnAddSvClick();
        else if(e.getSource().equals(AddNvButton)) btnAddNvClick();
        else if(e.getSource().equals(UpdateButton)) btnUpdateClick();
        else if(e.getSource().equals(ChangePwButton1)) btnChangeClick();
        else if(e.getSource().equals(AddGvButton)) btnAddGvClick();    
        else if(e.getSource().equals(ThemAnhButton)) chonAnh();
        else{
            int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn chắc chắn muốn đăng xuất không?","Thông báo",JOptionPane.YES_NO_OPTION);
            if(choice == JOptionPane.YES_OPTION){
                GD_DangNhap winD_DangNhap= new GD_DangNhap();
                winD_DangNhap.setLocationRelativeTo(null);
                winD_DangNhap.setVisible(true);
                this.dispose();
            }
        }
    }
    public void btnAddSvClick()
    {
        GD_ThemSinhVien winD_ThemSinhVien = new GD_ThemSinhVien(nhanVien);
        winD_ThemSinhVien.setLocationRelativeTo(null);
        winD_ThemSinhVien.setVisible(true);
        this.dispose();
    }
    public void btnAddNvClick()
    {
        GD_ThemNhanVien winD = new GD_ThemNhanVien(nhanVien);
        winD.setLocationRelativeTo(null);
        winD.setVisible(true);
        this.dispose();
    }
    public void btnUpdateClick()
    {
        GD_SuaSinhVien winD = new GD_SuaSinhVien(nhanVien);
        winD.setLocationRelativeTo(null);
        winD.setVisible(true);
        this.dispose();
    }
    public void btnChangeClick()
    {
        GD_DoiMk winD = new GD_DoiMk(nhanVien);
        winD.setLocationRelativeTo(null);
        winD.setVisible(true);
        this.dispose();
    }
    public void btnAddGvClick()
    {
        GD_ThemGiangVien winD = new GD_ThemGiangVien(nhanVien);
        winD.setLocationRelativeTo(null);
        winD.setVisible(true);
        this.dispose();
    }
    public void chonAnh()
    {
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Chọn ảnh đại diện");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result =  chooser.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            selectFile = chooser.getSelectedFile();
            try {
                Image img = ImageIO.read(selectFile);
                AvatarLabel.setIcon(new ImageIcon(img.getScaledInstance(150, 150, Image.SCALE_SMOOTH)));
                AvatarLabel.setText("");
                nhanVienDAO.updateAvatar(MsvLabel.getText(),selectFile);
                JOptionPane.showMessageDialog(rootPane, "Cập nhập ảnh thành công !");
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(rootPane, "Lỗi thực thi");
                e.printStackTrace();
            }
            
        }
    }
}
