
package view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.InputStream;
import java.util.Properties;
import model.TaiKhoan;



public class GD_Menu_Admin extends javax.swing.JFrame implements ActionListener{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GD_Menu_Admin.class.getName());

    
    
    public GD_Menu_Admin() {
        initComponents();

        pack();
        Properties prop = new Properties();
        try {
            InputStream input = getClass().getResourceAsStream("/config.properties");
            if(input != null) {
                prop.load(input);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    // Lấy giá trị màu background
        String bgColor = prop.getProperty("backgroundColor", "255,255,255"); // default trắng
        String[] rgb = bgColor.split(",");
        int r = Integer.parseInt(rgb[0].trim());
        int g = Integer.parseInt(rgb[1].trim());
        int b = Integer.parseInt(rgb[2].trim());

    // Set màu background cho JFrame
        getContentPane().setBackground(new Color(r, g, b));
        AddSvButton.addActionListener(this);
        RemoveSvButton.addActionListener(this);
        UpdateSvButton.addActionListener(this);
        ShowSvButton.addActionListener(this);
        AddAccButton.addActionListener(this);
        UpdateTkbButton.addActionListener(this);
        BackButton.addActionListener(this);
        CapNhapDiemButton.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel1 = new javax.swing.JLabel();
          AddSvButton = new javax.swing.JButton();
          RemoveSvButton = new javax.swing.JButton();
          UpdateSvButton = new javax.swing.JButton();
          ShowSvButton = new javax.swing.JButton();
          AddAccButton = new javax.swing.JButton();
          UpdateTkbButton = new javax.swing.JButton();
          BackButton = new javax.swing.JButton();
          CapNhapDiemButton = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setTitle("QUẢN LÝ SINH VIÊN [Admin]");
          setBackground(new java.awt.Color(255, 255, 255));

          jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
          jLabel1.setForeground(new java.awt.Color(255, 0, 51));
          jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel1.setText("MENU");
          jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

          AddSvButton.setText("Thêm sinh viên");

          RemoveSvButton.setText("Xóa sinh viên");

          UpdateSvButton.setText("Cập nhập SV");

          ShowSvButton.setText("Tất cả sinh viên");
          ShowSvButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ShowSvButtonActionPerformed(evt);
               }
          });

          AddAccButton.setText("Thêm tài khoản");
          AddAccButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AddAccButtonActionPerformed(evt);
               }
          });

          UpdateTkbButton.setText("Cập nhâp TKB");
          UpdateTkbButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    UpdateTkbButtonActionPerformed(evt);
               }
          });

          BackButton.setText("Đăng xuất");

          CapNhapDiemButton.setText("Cập nhập điểm ");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(BackButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addGroup(layout.createSequentialGroup()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(RemoveSvButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(UpdateSvButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(AddSvButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                                   .addComponent(CapNhapDiemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(AddAccButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(UpdateTkbButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(ShowSvButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGap(80, 80, 80))
          );

          layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AddSvButton, ShowSvButton});

          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(BackButton))
                    .addGap(55, 55, 55)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(AddSvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(ShowSvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addComponent(AddAccButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                         .addComponent(RemoveSvButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(UpdateSvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(UpdateTkbButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(CapNhapDiemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(48, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

    private void ShowSvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowSvButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowSvButtonActionPerformed

    private void UpdateTkbButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateTkbButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateTkbButtonActionPerformed

    private void AddAccButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAccButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddAccButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new GD_Menu_Admin(taiKhoan).setVisible(true));
    }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton AddAccButton;
     private javax.swing.JButton AddSvButton;
     private javax.swing.JButton BackButton;
     private javax.swing.JButton CapNhapDiemButton;
     private javax.swing.JButton RemoveSvButton;
     private javax.swing.JButton ShowSvButton;
     private javax.swing.JButton UpdateSvButton;
     private javax.swing.JButton UpdateTkbButton;
     private javax.swing.JLabel jLabel1;
     // End of variables declaration//GEN-END:variables
    @Override
    public void actionPerformed(ActionEvent e)
    {
        if(e.getSource().equals(AddSvButton)) btnThemSinhVien();
        else if(e.getSource().equals(RemoveSvButton)) btnXoaSinhVien();
        else if(e.getSource().equals(UpdateSvButton)) btnCapNhapSinhVien();
        else if(e.getSource().equals(ShowSvButton)) btnTatCaSinhVien();
        else if(e.getSource().equals(AddAccButton)) btnThemTaiKhoan();
        else if(e.getSource().equals(CapNhapDiemButton)) btnCapNhapDiemClick();
        else if(e.getSource().equals(BackButton))
        {
            GD_DangNhap winD_DangNhap = new GD_DangNhap();
            winD_DangNhap.setLocationRelativeTo(null);
            winD_DangNhap.setVisible(true);
            this.dispose();
        }
        else btnCapNhapTkb();
    }
    public void btnThemSinhVien()
    {
        GD_ThemSinhVien winThemSinhVien = new GD_ThemSinhVien();
        winThemSinhVien.setLocationRelativeTo(null);
        winThemSinhVien.setVisible(true);
        this.dispose();
    }
    public void btnXoaSinhVien()
    {
        GD_XoaSinhVien winD_XoaSinhVien = new GD_XoaSinhVien();
        winD_XoaSinhVien.setLocationRelativeTo(null);
        winD_XoaSinhVien.setVisible(true);
        this.dispose();
    }
    public void btnCapNhapSinhVien()
    {
        GD_SuaSinhVien winD_SuaSinhVien = new GD_SuaSinhVien();
        winD_SuaSinhVien.setLocationRelativeTo(null);
        winD_SuaSinhVien.setVisible(true);
        this.dispose();
    }
    public void btnTatCaSinhVien()
    {
        new GD_ShowSinhVien().setVisible(true);
        this.dispose();
    }
    public void btnThemTaiKhoan()
    {
        GD_ThemTaiKhoan winD_ThemTaiKhoan = new GD_ThemTaiKhoan();
        winD_ThemTaiKhoan.setLocationRelativeTo(null);
        winD_ThemTaiKhoan.setVisible(true);
        this.dispose();
    }
    public void btnCapNhapTkb()
    {
        GD_UpdateTkb winD_UpdateTkb = new GD_UpdateTkb();
        winD_UpdateTkb.setLocationRelativeTo(null);
        winD_UpdateTkb.setVisible(true);
        this.dispose();
    }
    public void btnCapNhapDiemClick()
    {
        GD_CapNhapDiem winCapNhapDiem = new GD_CapNhapDiem();
        winCapNhapDiem.setLocationRelativeTo(null);
        winCapNhapDiem.setVisible(true);
        this.dispose();
    }
    
   
}
