
package view;

import controller.SinhVienDAO;
import controller.TienTrinhDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import model.SinhVien;
import java.io.File;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



public class GD_Menu_SV extends javax.swing.JFrame implements ActionListener{
    public SinhVien sinhVien;
    private File selectFile;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GD_Menu_SV.class.getName());

    private SinhVienDAO sinhVienDAO;
    private TienTrinhDAO tienTrinhDAO;
    
    public GD_Menu_SV(SinhVien s) {
        initComponents();
        
        sinhVienDAO = new SinhVienDAO();
        tienTrinhDAO = new TienTrinhDAO();
        
        sinhVien = s;
        BackButton.addActionListener(this);
        DoiMkButton.addActionListener(this);
        XemTkbButton.addActionListener(this);
        XemTienTrinhHocButton.addActionListener(this);
        DanhSachLopButton.addActionListener(this);
        ThemAnhButton.addActionListener(this);
        TenLabel.setText(s.getName());
        MsvLabel.setText(s.getId());
        ClassLabel.setText(s.getMainClass());
        ChuyenNganhLabel.setText(s.getMajor());
        GioiTinhLabel.setText(s.getSex());
        NgaySinhLabel.setText(s.getDob().toString());
        DiaChiLabel.setText(s.getAddress());
        NamHocLabel.setText(String.valueOf(s.getSchoolYear()));
        SoDienThoaiLabel.setText(s.getPhone());
        TrangThaiLabel.setText(s.getStatus());
        EmailLabel.setText(s.getEmail());
        CpaLabel.setText(String.valueOf(tienTrinhDAO.getCpa(s)));
        ImageIcon avatar = sinhVienDAO.getAvatar(MsvLabel.getText());
        if (avatar != null) {
            AvatarLabel.setIcon(avatar);
            AvatarLabel.setText("");
        } else {
            AvatarLabel.setIcon(null);
            AvatarLabel.setText("Chưa có ảnh");
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        XemTkbButton = new javax.swing.JButton();
        TenLabel = new javax.swing.JLabel();
        MsvLabel = new javax.swing.JLabel();
        AvatarLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        DoiMkButton = new javax.swing.JButton();
        LopLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ChuyenNganhLabel = new javax.swing.JLabel();
        GioiTinhLabel = new javax.swing.JLabel();
        NgaySinhLabel = new javax.swing.JLabel();
        DiaChiLabel = new javax.swing.JLabel();
        NamHocLabel = new javax.swing.JLabel();
        SoDienThoaiLabel = new javax.swing.JLabel();
        TrangThaiLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        CpaLabel = new javax.swing.JLabel();
        ClassLabel = new javax.swing.JLabel();
        XemTienTrinhHocButton = new javax.swing.JButton();
        DanhSachLopButton = new javax.swing.JButton();
        ThemAnhButton = new javax.swing.JButton();

        jLabel17.setText("jLabel17");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ SINH VIÊN [USER]");
        setBackground(new java.awt.Color(255, 255, 255));

        XemTkbButton.setText("Xem TKB");
        XemTkbButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XemTkbButtonActionPerformed(evt);
            }
        });

        TenLabel.setBackground(new java.awt.Color(255, 255, 255));
        TenLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TenLabel.setOpaque(true);

        MsvLabel.setBackground(new java.awt.Color(255, 255, 255));
        MsvLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MsvLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MsvLabel.setOpaque(true);

        AvatarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AvatarLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\nguye\\Downloads\\avatar.jpg")); // NOI18N
        AvatarLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BackButton.setText("Đăng xuất");

        DoiMkButton.setText("Đổi mật khẩu");

        LopLabel.setBackground(new java.awt.Color(255, 255, 255));
        LopLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LopLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LopLabel.setOpaque(true);

        jLabel3.setText("Chuyên ngành:");

        jLabel4.setText("Giới tính:");

        jLabel5.setText("Ngày sinh:");

        jLabel6.setText("Địa chỉ:");

        jLabel7.setText("Kì học:");

        jLabel8.setText("Số điện thoại:");

        jLabel9.setText("Trạng thái:");

        jLabel10.setText("Email:");

        jLabel11.setText("CPA:");

        ChuyenNganhLabel.setBackground(new java.awt.Color(255, 255, 255));
        ChuyenNganhLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ChuyenNganhLabel.setOpaque(true);

        GioiTinhLabel.setBackground(new java.awt.Color(255, 255, 255));
        GioiTinhLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GioiTinhLabel.setOpaque(true);

        NgaySinhLabel.setBackground(new java.awt.Color(255, 255, 255));
        NgaySinhLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NgaySinhLabel.setOpaque(true);

        DiaChiLabel.setBackground(new java.awt.Color(255, 255, 255));
        DiaChiLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DiaChiLabel.setOpaque(true);

        NamHocLabel.setBackground(new java.awt.Color(255, 255, 255));
        NamHocLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NamHocLabel.setOpaque(true);

        SoDienThoaiLabel.setBackground(new java.awt.Color(255, 255, 255));
        SoDienThoaiLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SoDienThoaiLabel.setOpaque(true);

        TrangThaiLabel.setBackground(new java.awt.Color(255, 255, 255));
        TrangThaiLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TrangThaiLabel.setOpaque(true);

        EmailLabel.setBackground(new java.awt.Color(255, 255, 255));
        EmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailLabel.setOpaque(true);

        CpaLabel.setBackground(new java.awt.Color(255, 255, 255));
        CpaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CpaLabel.setOpaque(true);

        ClassLabel.setBackground(new java.awt.Color(255, 255, 255));
        ClassLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ClassLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ClassLabel.setOpaque(true);

        XemTienTrinhHocButton.setText("Xem tiến trình học");

        DanhSachLopButton.setText("Danh sách lớp");

        ThemAnhButton.setText("Thêm ảnh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(DanhSachLopButton)
                .addGap(18, 18, 18)
                .addComponent(XemTienTrinhHocButton)
                .addGap(18, 18, 18)
                .addComponent(DoiMkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(XemTkbButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MsvLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(ClassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LopLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(AvatarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ChuyenNganhLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GioiTinhLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NgaySinhLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DiaChiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NamHocLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SoDienThoaiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TrangThaiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CpaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(ThemAnhButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackButton)
                .addGap(23, 23, 23)
                .addComponent(ThemAnhButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AvatarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ChuyenNganhLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(GioiTinhLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(NgaySinhLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(DiaChiLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(NamHocLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MsvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(ClassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LopLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(SoDienThoaiLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TrangThaiLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(EmailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(CpaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DoiMkButton)
                            .addComponent(XemTkbButton)
                            .addComponent(XemTienTrinhHocButton)
                            .addComponent(DanhSachLopButton))
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void XemTkbButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XemTkbButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XemTkbButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new GD_Menu_SV(SinhVien s).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvatarLabel;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel ChuyenNganhLabel;
    private javax.swing.JLabel ClassLabel;
    private javax.swing.JLabel CpaLabel;
    private javax.swing.JButton DanhSachLopButton;
    private javax.swing.JLabel DiaChiLabel;
    private javax.swing.JButton DoiMkButton;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel GioiTinhLabel;
    private javax.swing.JLabel LopLabel;
    private javax.swing.JLabel MsvLabel;
    private javax.swing.JLabel NamHocLabel;
    private javax.swing.JLabel NgaySinhLabel;
    private javax.swing.JLabel SoDienThoaiLabel;
    private javax.swing.JLabel TenLabel;
    private javax.swing.JButton ThemAnhButton;
    private javax.swing.JLabel TrangThaiLabel;
    private javax.swing.JButton XemTienTrinhHocButton;
    private javax.swing.JButton XemTkbButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
    @Override
    public void actionPerformed(ActionEvent e)
    {
        if(e.getSource().equals(DoiMkButton)) btnDoiMkClick();
        else if(e.getSource().equals(XemTkbButton)) btnXemTkbClick();
        else if(e.getSource().equals(XemTienTrinhHocButton)) btnXemTthClick();
        else if(e.getSource().equals(DanhSachLopButton)) btnDanhSachLopClick();
        else if(e.getSource().equals(ThemAnhButton)) chonAnh();
        else{
            GD_DangNhap winD_DangNhap= new GD_DangNhap();
            winD_DangNhap.setLocationRelativeTo(null);
            winD_DangNhap.setVisible(true);
            this.dispose();
        }
    }
    public void btnDoiMkClick()
    {
        GD_DoiMk winD_DoiMk = new GD_DoiMk(sinhVien);
        winD_DoiMk.setLocationRelativeTo(null);
        winD_DoiMk.setVisible(true);
        this.dispose();
    }
    public void btnXemTkbClick()
    {
        GD_XemTkb winD_XemTkb = new GD_XemTkb(sinhVien);
        winD_XemTkb.setLocationRelativeTo(null);
        winD_XemTkb.setVisible(true);
        this.dispose();
    }
    public void btnXemTthClick()
    {
        GD_XemTienTrinh winD_XemTienTrinh = new GD_XemTienTrinh(sinhVien);
        winD_XemTienTrinh.setLocationRelativeTo(null);
        winD_XemTienTrinh.setVisible(true);
        this.dispose();
    }
    public void btnDanhSachLopClick()
    {
        GD_SVCungLop winCungLop = new GD_SVCungLop(sinhVien);
        winCungLop.setLocationRelativeTo(null);
        winCungLop.setVisible(true);
        this.dispose();
    }
    public void chonAnh()
    {
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Chọn ảnh đại diện");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result =  chooser.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            selectFile = chooser.getSelectedFile();
            try {
                Image img = ImageIO.read(selectFile);
                AvatarLabel.setIcon(new ImageIcon(img.getScaledInstance(150, 150, Image.SCALE_SMOOTH)));
                AvatarLabel.setText("");
                sinhVienDAO.updateAvatar(MsvLabel.getText(),selectFile);
                JOptionPane.showMessageDialog(rootPane, "Cập nhập ảnh thành công !");
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(rootPane, "Lỗi thực thi");
                e.printStackTrace();
            }
            
        }
    }
}
