
package view;

import controller.GiangVienDAO;
import controller.NhanVienDAO;
import controller.SinhVienDAO;
import controller.TienTrinhDAO;
import controller.TkbDAO;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import model.SinhVien;
import java.io.File;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import java.awt.Image;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Properties;
import javax.swing.AbstractCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Spring;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import model.GiangVien;
import model.LopHocPhan;



public class GD_Menu_GV extends javax.swing.JFrame implements ActionListener{
    public GiangVien giangVien;
    private File selectFile;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GD_Menu_GV.class.getName());

    private SinhVienDAO sinhVienDAO;
    private TienTrinhDAO tienTrinhDAO;
    private DefaultTableModel model;
    private ArrayList<LopHocPhan> list;
    public GD_Menu_GV(GiangVien s) {
        initComponents();
        pack();
        Properties prop = new Properties();
        try {
            InputStream input = getClass().getResourceAsStream("/config.properties");
            if(input != null) {
                prop.load(input);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        String bgColor = prop.getProperty("backgroundColor", "255,255,255"); // default trắng
        String[] rgb = bgColor.split(",");
        int r = Integer.parseInt(rgb[0].trim());
        int g = Integer.parseInt(rgb[1].trim());
        int b = Integer.parseInt(rgb[2].trim());

    
        getContentPane().setBackground(new Color(r, g, b));
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        sinhVienDAO = new SinhVienDAO();
        tienTrinhDAO = new TienTrinhDAO();
        //---------------------------------------------
        giangVien = s;
        
        BackButton.addActionListener(this);
        DoiMkButton.addActionListener(this);
        ThemAnhButton.addActionListener(this);
        DangKiButton.addActionListener(this);
        NghiButton.addActionListener(this);
        TenLabel.setText(s.getName());
        KhoaLabel1.setText(s.getKhoa());
        DobLabel.setText(s.getDOB());
        
        ImageIcon avatar =  new GiangVienDAO().getAvatar(giangVien.getID());
        if (avatar != null) {
            AvatarLabel.setIcon(avatar);
            AvatarLabel.setText("");
        } else {
            AvatarLabel.setIcon(null);
            AvatarLabel.setText("Chưa có ảnh");
        }
        model = (DefaultTableModel) LopHocPhanTable.getModel();
        model.setColumnIdentifiers(new Object[]{
            "Mã học phần","Mã môn","Phòng Học","Giảng viên","Tiết bắt đầu","Số tiết","Thứ","Thời gian","Thao tác"
        });
        list = new TkbDAO().getLHP2GV(giangVien.getID());
        ShowData(list);
        int columIndex = 8;
        LopHocPhanTable.getColumnModel().getColumn(columIndex).setCellRenderer(new ButtonRenderer3());
        LopHocPhanTable.getColumnModel().getColumn(columIndex).setCellEditor(new ButtonEditor3(giangVien,list));
    }
    public void ShowData(ArrayList<LopHocPhan> list)
    {
        for(LopHocPhan i : list)
        {
            GiangVien g = new GiangVienDAO().getGiangVien(i.getMaGV());
            model.addRow(new Object[]{
                i.getMaLHP(),i.getMaMon(),i.getPhong(),g.getName(),String.valueOf(i.getTietBatDau()),String.valueOf(i.getSoTiet()),i.getThu(),i.getThoiGian(),"Cập nhập"
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        TenLabel = new javax.swing.JLabel();
        DobLabel = new javax.swing.JLabel();
        AvatarLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        DoiMkButton = new javax.swing.JButton();
        ThemAnhButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LopHocPhanTable = new javax.swing.JTable();
        DangKiButton = new javax.swing.JButton();
        KhoaLabel1 = new javax.swing.JLabel();
        NghiButton = new javax.swing.JButton();

        jLabel17.setText("jLabel17");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ SINH VIÊN [USER]");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TenLabel.setBackground(new java.awt.Color(255, 255, 255));
        TenLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TenLabel.setOpaque(true);
        getContentPane().add(TenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 180, 22));

        DobLabel.setBackground(new java.awt.Color(255, 255, 255));
        DobLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DobLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DobLabel.setOpaque(true);
        getContentPane().add(DobLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 180, 20));

        AvatarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AvatarLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(AvatarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 127, 140));

        BackButton.setText("Đăng xuất");
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        DoiMkButton.setText("Đổi mật khẩu");
        getContentPane().add(DoiMkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 590, 106, -1));

        ThemAnhButton.setText("Thêm ảnh");
        ThemAnhButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemAnhButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ThemAnhButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRANG GIẢNG VIÊN");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 320, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Các lớp đang giảng dạy:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        LopHocPhanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(LopHocPhanTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 860, 440));

        DangKiButton.setText("Đăng kí lớp giảng dạy");
        getContentPane().add(DangKiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 590, -1, -1));

        KhoaLabel1.setBackground(new java.awt.Color(255, 255, 255));
        KhoaLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        KhoaLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KhoaLabel1.setOpaque(true);
        getContentPane().add(KhoaLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 180, 20));

        NghiButton.setText("Nghỉ dạy");
        getContentPane().add(NghiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThemAnhButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemAnhButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThemAnhButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new GD_Menu_SV(SinhVien s).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvatarLabel;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton DangKiButton;
    private javax.swing.JLabel DobLabel;
    private javax.swing.JButton DoiMkButton;
    private javax.swing.JLabel KhoaLabel1;
    private javax.swing.JTable LopHocPhanTable;
    private javax.swing.JButton NghiButton;
    private javax.swing.JLabel TenLabel;
    private javax.swing.JButton ThemAnhButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void actionPerformed(ActionEvent e)
    {
        if(e.getSource().equals(DoiMkButton)) btnDoiMkClick();
        else if(e.getSource().equals(DangKiButton)) btnDkClick();
        else if(e.getSource().equals(ThemAnhButton)) chonAnh();
        else if(e.getSource().equals(NghiButton)) btnNghiClick();
        else{
            GD_DangNhap winD_DangNhap= new GD_DangNhap();
            winD_DangNhap.setLocationRelativeTo(null);
            winD_DangNhap.setVisible(true);
            this.dispose();
        }
    }
    public void btnDkClick()
    {
        int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn chắc chắn muốn đăng xuất không?","Thông báo",JOptionPane.YES_NO_OPTION);
        if(choice == JOptionPane.YES_OPTION){
            GD_DangKiLopGiangDay winD_DangKiLopGiangDay = new GD_DangKiLopGiangDay(giangVien);
            winD_DangKiLopGiangDay.setLocationRelativeTo(null);
            winD_DangKiLopGiangDay.setVisible(true);
            this.dispose();
        }
        
    }
    public void btnDoiMkClick()
    {
        GD_DoiMk2 winD_DoiMk = new GD_DoiMk2(giangVien);
        winD_DoiMk.setLocationRelativeTo(null);
        winD_DoiMk.setVisible(true);
        
    }
    public void btnNghiClick()
    {
        int choice = JOptionPane.showConfirmDialog(rootPane, "Thao tác này sẽ xóa tất cả dữ liệu của bạn, bạn chắc chắn muốn nghỉ chứ ?","Thông báo",JOptionPane.YES_NO_OPTION);
        if(choice == JOptionPane.YES_OPTION)
        {
            
            if(new GiangVienDAO().xoaGV(giangVien)==true)
            {
                JOptionPane.showMessageDialog(rootPane, "Cảm ơn vì những đóng góp của bạn :3");
                GD_DangNhap wiD_DangNhap = new GD_DangNhap();
                wiD_DangNhap.setLocationRelativeTo(null);
                wiD_DangNhap.setVisible(true);
                this.dispose();
            }
        }
        
    }

   
    public void chonAnh()
    { 
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Chọn ảnh đại diện");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result =  chooser.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            selectFile = chooser.getSelectedFile();
            try {
                Image img = ImageIO.read(selectFile);
                AvatarLabel.setIcon(new ImageIcon(img.getScaledInstance(150, 150, Image.SCALE_SMOOTH)));
                AvatarLabel.setText("");
                new GiangVienDAO().updateAvatar(giangVien.getID(),selectFile);
                JOptionPane.showMessageDialog(rootPane, "Cập nhập ảnh thành công !");
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(rootPane, "Lỗi thực thi");
                e.printStackTrace();
            }
            
        }
    }
}
class ButtonRenderer3 extends JButton implements TableCellRenderer
{
    public ButtonRenderer3()
    {
        setOpaque(true);
        
    }
    @Override
    public Component getTableCellRendererComponent(JTable table,Object value,boolean isSelected, boolean hasFocus,int row, int column)
    {
        setText((value == null)? "Đăng kí": value.toString());
        return this;
    }
}
class ButtonEditor3 extends AbstractCellEditor implements TableCellEditor, ActionListener
{
    private JButton button;
    private JTable table;
    private int currentRow;
    private GiangVien giangVien;
    private ArrayList<LopHocPhan> list;
    public ButtonEditor3(GiangVien s,ArrayList<LopHocPhan> list)
    {
        giangVien =s;
        this.list = list;
        button = new JButton("Cập nhập");
        button.setOpaque(true);
        button.addActionListener(this);
    }
    @Override
    public Component getTableCellEditorComponent(JTable table, Object value,boolean isSelected, int row, int column)
    {
        this.table = table;
        this.currentRow = row;
        button.setText((value == null)? "Cập nhập":value.toString());
        return button;
    }
    @Override
    public Object getCellEditorValue()
    {
        return button.getText();
    }
    @Override
    public void actionPerformed(ActionEvent e)
    {
        GD_CapNhapDiem winCapNhapDiem = new GD_CapNhapDiem(list.get(currentRow));
        winCapNhapDiem.setLocationRelativeTo(null);
        winCapNhapDiem.setVisible(true);
    }

    @Override
    protected void fireEditingStopped() {
        super.fireEditingStopped(); 
    }
    
}