
package view;

import controller.SinhVienDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import model.SinhVien;



public class GD_SuaSinhVien extends javax.swing.JFrame implements ActionListener{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GD_SuaSinhVien.class.getName());

    private SinhVienDAO sinhVienDAO;
    private SinhVien s;
    
    public GD_SuaSinhVien() {
        initComponents();
        
        sinhVienDAO = new SinhVienDAO();
        gioitinh = new ButtonGroup();
        trangthai = new ButtonGroup();
        BackButton.addActionListener(this);
        UpdateButton.addActionListener(this);
        TimKiemButton.addActionListener(this);
        XoaSinhVienButton.addActionListener(this);
        CapNhapDiemButton.addActionListener(this);
        gioitinh.add(MaleCheckBox);
        gioitinh.add(FemaleCheckBox);
        trangthai.add(StudyingCheckBox);
        trangthai.add(GraduatedCheckBox);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        IdTextField = new javax.swing.JTextField();
        TimKiemButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        SchoolYearTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        PhoneTextField = new javax.swing.JTextField();
        AddressTextField = new javax.swing.JTextField();
        ClassTextField = new javax.swing.JTextField();
        NameTextField = new javax.swing.JTextField();
        MajorComboBox = new javax.swing.JComboBox<>();
        MaleCheckBox = new javax.swing.JCheckBox();
        FemaleCheckBox = new javax.swing.JCheckBox();
        StudyingCheckBox = new javax.swing.JCheckBox();
        GraduatedCheckBox = new javax.swing.JCheckBox();
        XoaSinhVienButton = new javax.swing.JButton();
        CapNhapDiemButton = new javax.swing.JButton();
        ngaySpinner = new javax.swing.JSpinner();
        thangSpinner = new javax.swing.JSpinner();
        namSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CẬP NHẬP THÔNG TIN ");

        BackButton.setText("Quay lại");

        jLabel2.setText("MSV:");

        TimKiemButton.setText("Tìm kiếm");

        jLabel3.setText("Name:");

        jLabel4.setText("Sex:");

        jLabel5.setText("DOB:");

        jLabel6.setText("Class:");

        jLabel7.setText("Address:");

        jLabel8.setText("Phone:");

        jLabel9.setText("Email:");

        jLabel10.setText("Status:");

        jLabel11.setText("Major:");

        jLabel12.setText("School Year:");

        UpdateButton.setText("Cập nhập");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        MajorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "QT", "MK", "BC", "KHMT" }));

        MaleCheckBox.setText("Male");

        FemaleCheckBox.setText("Female");

        StudyingCheckBox.setText("Studying");

        GraduatedCheckBox.setText("Graduated");

        XoaSinhVienButton.setText("Xóa sinh viên");

        CapNhapDiemButton.setText("Cập nhập điểm");

        ngaySpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        thangSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        namSpinner.setModel(new javax.swing.SpinnerNumberModel(1900, 1900, 2200, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(TimKiemButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BackButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(IdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(SchoolYearTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                            .addComponent(EmailTextField)
                                            .addComponent(PhoneTextField)
                                            .addComponent(AddressTextField)
                                            .addComponent(ClassTextField)
                                            .addComponent(NameTextField)
                                            .addComponent(MajorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(StudyingCheckBox)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(GraduatedCheckBox))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(ngaySpinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                    .addComponent(MaleCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 0, 0)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(FemaleCheckBox)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(thangSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, 0)
                                                        .addComponent(namSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(UpdateButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(XoaSinhVienButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(CapNhapDiemButton)))))))
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackButton)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(IdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TimKiemButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(MaleCheckBox)
                        .addComponent(FemaleCheckBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ngaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thangSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ClassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(PhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(StudyingCheckBox)
                    .addComponent(GraduatedCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(MajorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(SchoolYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateButton)
                    .addComponent(XoaSinhVienButton)
                    .addComponent(CapNhapDiemButton))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GD_SuaSinhVien().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CapNhapDiemButton;
    private javax.swing.JTextField ClassTextField;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JCheckBox FemaleCheckBox;
    private javax.swing.JCheckBox GraduatedCheckBox;
    private javax.swing.JTextField IdTextField;
    private javax.swing.JComboBox<String> MajorComboBox;
    private javax.swing.JCheckBox MaleCheckBox;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField PhoneTextField;
    private javax.swing.JTextField SchoolYearTextField;
    private javax.swing.JCheckBox StudyingCheckBox;
    private javax.swing.JButton TimKiemButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton XoaSinhVienButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner namSpinner;
    private javax.swing.JSpinner ngaySpinner;
    private javax.swing.JSpinner thangSpinner;
    // End of variables declaration//GEN-END:variables
    private ButtonGroup gioitinh;
    private ButtonGroup trangthai;
    @Override
    public void actionPerformed(ActionEvent e)
    {
        if(e.getSource().equals(TimKiemButton)) btnTimKiemClick();
        else if(e.getSource().equals(UpdateButton)) btnCapNhapClick();
        else if(e.getSource().equals(XoaSinhVienButton)) btnXoaSinhVienClick();
        else if(e.getSource().equals(CapNhapDiemButton)) btnCapNhapDiemClick();
        else
        {
            GD_Menu_Admin winAdmin = new GD_Menu_Admin();
            winAdmin.setLocationRelativeTo(null);
            winAdmin.setVisible(true);
            this.dispose();
        }
    }
    public void btnTimKiemClick()
    {
        s = sinhVienDAO.getSinhVien(IdTextField.getText());
        IdTextField.setText(s.getId());
        NameTextField.setText(s.getName());
        boolean check = s.getStatus().equals("Studying");
        StudyingCheckBox.setSelected(check);
        GraduatedCheckBox.setSelected(!check);
        String dob = new SimpleDateFormat("dd/MM/yyyy").format(s.getDob());
        String[] ss = dob.split("/");
        ngaySpinner.setValue(Integer.parseInt(ss[0]));
        thangSpinner.setValue(Integer.parseInt(ss[1]));
        namSpinner.setValue(Integer.parseInt(ss[2]));
        ClassTextField.setText(s.getMainClass());
        AddressTextField.setText(s.getAddress());
        PhoneTextField.setText(s.getPhone());
        EmailTextField.setText(s.getEmail());
        check = s.getSex().equals("Male");
        MaleCheckBox.setSelected(check);
        FemaleCheckBox.setSelected(!check);
        if(s.getMajor().equals("IT")) MajorComboBox.setSelectedIndex(0);
        else if(s.getMajor().equals("QT")) MajorComboBox.setSelectedIndex(1);
        else if(s.getMajor().equals("MK")) MajorComboBox.setSelectedIndex(2);
        else if(s.getMajor().equals("BC")) MajorComboBox.setSelectedIndex(3);
        else if(s.getMajor().equals("KHMT")) MajorComboBox.setSelectedIndex(4);
        SchoolYearTextField.setText(String.valueOf(s.getSchoolYear()));
    }
    public void btnCapNhapClick()
    {
        String nganhhocbandau = s.getMajor();
        SinhVien sv = new SinhVien();
        sv.setId(IdTextField.getText());
        sv.setName(NameTextField.getText());
        if(MaleCheckBox.isSelected()) sv.setSex("Male");
        else sv.setSex("Female");
        try{
             sv.setDob(new SimpleDateFormat("dd/MM/yyyy").parse(ngaySpinner.getValue().toString() + "/" + thangSpinner.getValue().toString()+"/"+namSpinner.getValue().toString()));
        } catch(Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Sai định dạng ngày tháng");
        }
        sv.setMainClass(ClassTextField.getText());
        sv.setAddress(AddressTextField.getText());
        sv.setPhone(PhoneTextField.getText());
        sv.setEmail(EmailTextField.getText());
        if(StudyingCheckBox.isSelected()) sv.setStatus("Studying");
        else sv.setStatus("Graduated");
        sv.setMajor((String)MajorComboBox.getSelectedItem());
        try {
            sv.setSchoolYear(Integer.parseInt(SchoolYearTextField.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Định dạng số không chính xác !");
        }
        if(!nganhhocbandau.equals(sv.getMajor()))
        {
            if(sinhVienDAO.CapNhap(sv))
            {
                JOptionPane.showMessageDialog(rootPane, "Cập nhập thông tin thành công !");
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Cập nhập thông tin thất bại !");
            }
        }
        else{
            if(sinhVienDAO.CapNhap2(sv))
            {
                JOptionPane.showMessageDialog(rootPane, "Cập nhập thông tin thành công !");
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Cập nhập thông tin thất bại !");
            }
        }
      
        
    }
    public void btnCapNhapDiemClick()
    {
        GD_CapNhapDiem winCapNhapDiem = new GD_CapNhapDiem(s);
        winCapNhapDiem.setLocationRelativeTo(null);
        winCapNhapDiem.setVisible(true);
    }
    public void btnXoaSinhVienClick()
    {
        int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn chắc chắn muốn xóa sinh viên này không ?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if(choice == JOptionPane.YES_OPTION)
        {
            if(new SinhVienDAO().XoaSinhVien(IdTextField.getText()))
            {
                JOptionPane.showMessageDialog(rootPane, "Xóa sinh viên thành công");
                IdTextField.setText("");
                NameTextField.setText("");
                MaleCheckBox.setSelected(false);
                FemaleCheckBox.setSelected(false);
                ngaySpinner.setValue(1);
                thangSpinner.setValue(1);
                namSpinner.setValue(1900);
                ClassTextField.setText("");
                AddressTextField.setText("");
                PhoneTextField.setText("");
                EmailTextField.setText("");
                StudyingCheckBox.setSelected(false);
                GraduatedCheckBox.setSelected(false);
                SchoolYearTextField.setText("");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Thông tin không tồn tại");
            }
        }
        
    }
}
