
package view;

import controller.SinhVienDAO;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.AbstractCellEditor;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import model.SinhVien;



public class GD_SVCungLop1 extends javax.swing.JFrame implements ActionListener{
    SinhVien sinhVien;
    ArrayList<SinhVien> list;
    DefaultTableModel model;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GD_SVCungLop1.class.getName());

    /**
     * Creates new form GD_SVCungLop
     */
    public GD_SVCungLop1(SinhVien sinhVien) {
        initComponents();
        this.sinhVien = sinhVien;
        BackButton.addActionListener(this);
        model = (DefaultTableModel) SvTable.getModel();
        list = new SinhVienDAO().getlistSinhVien();
        int cnt = 0;
        model.setColumnIdentifiers(new Object[]{
            "STT","MSV","Tên","Giới tính","Ngày sinh","Lớp","Địa chỉ","Số điện thoại","Email","Trạng thái","Chuyên ngành","Kì học",
        });
        for(SinhVien i : list)
        {
            if(i.getMainClass().equals(sinhVien.getMainClass()))
            {
                model.addRow(new Object[]{
                    ++cnt,i.getId(),i.getName(),i.getSex(),i.getDob(),i.getMainClass(),i.getAddress(),i.getPhone(),i.getEmail(),i.getStatus(),i.getMajor(),i.getSchoolYear()
                });
            }
        }
        
        SvTable.setDefaultEditor(Object.class, null);
        SvTable.getColumnModel().getColumn(0).setPreferredWidth(35);
        SvTable.getColumnModel().getColumn(1).setPreferredWidth(80);
        SvTable.getColumnModel().getColumn(2).setPreferredWidth(115);
        SvTable.getColumnModel().getColumn(3).setPreferredWidth(55);
        SvTable.getColumnModel().getColumn(4).setPreferredWidth(75);
        SvTable.getColumnModel().getColumn(5).setPreferredWidth(70);
        SvTable.getColumnModel().getColumn(6).setPreferredWidth(60);
        SvTable.getColumnModel().getColumn(7).setPreferredWidth(60);
        SvTable.getColumnModel().getColumn(8).setPreferredWidth(60);
        SvTable.getColumnModel().getColumn(9).setPreferredWidth(60);
        SvTable.getColumnModel().getColumn(10).setPreferredWidth(40);
        SvTable.getColumnModel().getColumn(11).setPreferredWidth(40);
        
       
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        SvTable = new javax.swing.JTable();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SvTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(SvTable);

        BackButton.setText("Quay lại");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(914, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTable SvTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void actionPerformed(ActionEvent e)
    {
        if(e.getSource().equals(BackButton))
        {
            GD_Menu_SV1 winD_Menu_SV = new GD_Menu_SV1(sinhVien);
            winD_Menu_SV.setLocationRelativeTo(null);
            winD_Menu_SV.setVisible(true);
            this.dispose();
        }
    }

}
