
package view;

import controller.GiangVienDAO;
import controller.SinhVienDAO;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import model.SinhVien;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Properties;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import java.text.Normalizer;
import java.util.regex.Pattern;
import model.GiangVien;
import model.NhanVien;


public class GD_ThemGiangVien extends javax.swing.JFrame implements ActionListener{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GD_ThemGiangVien.class.getName());

    private GiangVienDAO giangVienDAO;
    private NhanVien nhanVien;
    public GD_ThemGiangVien(NhanVien s) {
        initComponents();
       
        
        GioiTinh = new ButtonGroup();
        giangVienDAO  = new GiangVienDAO();
        Add.addActionListener(this);
        ResetButton.addActionListener(this);
        BackButton.addActionListener(this);
        MajorComboBox.addItem("IT");
        MajorComboBox.addItem("BC");
        MajorComboBox.addItem("QTKD");
        MajorComboBox.addItem("KH");
        MajorComboBox.addItem("MKT");
        
        GioiTinh.add(MaleCheckBox);
        GioiTinh.add(FemaleCheckBox);
        nhanVien = s;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        PhoneTextField = new javax.swing.JTextField();
        MaleCheckBox = new javax.swing.JCheckBox();
        FemaleCheckBox = new javax.swing.JCheckBox();
        NameTextField = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        MajorComboBox = new javax.swing.JComboBox<>();
        DaySpinner = new javax.swing.JSpinner();
        MonthSpinner = new javax.swing.JSpinner();
        YearSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("QUẢN LÝ SINH VIÊN [Admin]");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÊM GIẢNG VIÊN");

        jLabel3.setText("Name:");

        jLabel4.setText("Sex:");

        jLabel5.setText("Date of birth:");

        jLabel8.setText("Phone Number:");

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        ResetButton.setText("Reset");

        MaleCheckBox.setText("Male");

        FemaleCheckBox.setText("Female");

        BackButton.setText("Quay lại");

        jLabel12.setText("Major:");

        DaySpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        MonthSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        YearSpinner.setModel(new javax.swing.SpinnerNumberModel(2000, 1900, 2500, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Add)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ResetButton)
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MajorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(MaleCheckBox)
                                    .addGap(18, 18, 18)
                                    .addComponent(FemaleCheckBox))
                                .addComponent(PhoneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                .addComponent(NameTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MonthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(YearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(72, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(MaleCheckBox)
                    .addComponent(FemaleCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(PhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(MajorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add)
                    .addComponent(ResetButton))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    /**
     * @param args the command line arguments
     */
    public String getEmail(String s, String q)
    {
        String nfdStr = Normalizer.normalize(s, Normalizer.Form.NFD);
        Pattern pattern = Pattern.compile("\\p{InCombiningDiacriticalMarks}+");
        String temp = pattern.matcher(nfdStr).replaceAll("");
        String sol = temp.replaceAll("Đ", "D").replaceAll("đ", "d");
        String[] arr = sol.split("\\s+");
        for(String i : arr) 
        {
            i.toUpperCase();
        }
        String res = String.valueOf(arr[arr.length-1].charAt(0));
        for(int i = 0;i<arr.length-1;i++)
        {
            res += arr[i].charAt(0);
        }
        res += "." + q + "@ptit.edu.vn";
        return res;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton BackButton;
    private javax.swing.JSpinner DaySpinner;
    private javax.swing.JCheckBox FemaleCheckBox;
    private javax.swing.JComboBox<String> MajorComboBox;
    private javax.swing.JCheckBox MaleCheckBox;
    private javax.swing.JSpinner MonthSpinner;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField PhoneTextField;
    private javax.swing.JButton ResetButton;
    private javax.swing.JSpinner YearSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    private ButtonGroup GioiTinh;
    @Override
    public void actionPerformed(ActionEvent e)
    {
        if(e.getSource().equals(Add)) btnAddClick();
        else if(e.getSource().equals(ResetButton)) btnResetClick();
        else
        {
            
            GD_Menu_Admin1 winAdmin = new GD_Menu_Admin1(nhanVien);
            winAdmin.setLocationRelativeTo(null);
            winAdmin.setVisible(true);
            this.dispose();
        }
    }
    public void btnAddClick()
    {
        GiangVien s = new GiangVien();
        ArrayList<GiangVien> list  = new GiangVienDAO().getListGV2Major();
        
        ArrayList<Integer> tmp = new ArrayList<>();
        for(GiangVien i : list)
        {
            
            int t3 = Integer.parseInt(i.getID().substring(2));
            tmp.add(t3);
            
        }
        int stt = tmp.size()+1;
        Collections.sort(tmp);
        for(int i = 0;i<tmp.size();i++)
        {
            if(i + 1 != tmp.get(i)){
                stt = i+1;
                break;
            }
        }
        s.setID("GV" + String.format("%03d", stt));
        s.setName(NameTextField.getText());
        if(MaleCheckBox.isSelected()) s.setGender("Male");
        else if(FemaleCheckBox.isSelected()) s.setGender("Female");
        s.setPhone(PhoneTextField.getText());
        s.setEmail(getEmail(NameTextField.getText(), s.getID()));
        s.setDOB(String.valueOf(DaySpinner.getValue())+"/"+String.valueOf(MonthSpinner.getValue())+"/"+String.valueOf(YearSpinner.getValue()));
        s.setKhoa((String)MajorComboBox.getSelectedItem());
       
        if(new GiangVienDAO().addGiangVien(s))
        {
            JOptionPane.showMessageDialog(rootPane, "Thêm thông tin thành công !");
        }
        else 
        {
            JOptionPane.showMessageDialog(rootPane, "Thêm thông tin thất bại !");
        }
    }
    public void btnResetClick()
    {
        
        NameTextField.setText("");
        MaleCheckBox.setSelected(false);
        FemaleCheckBox.setSelected(false);
       
        PhoneTextField.setText("");
  

    }
}
